export {
  AuthError,
  loginUser,
  getMe,
  getStoredToken,
  clearStoredToken,
  SessionError,
  createSession,
  openSession,
  listMySessions,
  startSession,
  joinSession,
  getSessionState,
  setCheckpointRole,
  addCompetitor,
} from './client';
export type {
  SportType,
  SessionStatus,
  CheckpointRole,
  CreateSessionInput,
  Session,
  JoinSessionResponse,
  SessionCheckpointState,
  SessionStateResponse,
  Competitor,
} from './client';
